export const metadata = {
  title: "Terms of Service — FunderReady",
};

export default function TermsOfServicePage() {
  return (
    <>
      <h1>Terms of Service</h1>
      <p className="text-sm text-zinc-500">Last updated: March 2026</p>

      <h2>1. Service Description</h2>
      <p>
        FunderReady is an AI-powered platform that helps users prepare and
        review funding applications. Users select a fund, fill in application
        questions, and submit for AI-generated review feedback including scores,
        inline comments, and improvement suggestions.
      </p>

      <h2>2. Eligibility</h2>
      <p>
        You must be at least 18 years old and have the legal capacity to enter
        into a binding agreement. By creating an account, you represent that you
        meet these requirements.
      </p>

      <h2>3. AI Disclaimer</h2>
      <p>
        <strong>
          AI reviews are suggestions only and do not constitute professional
          advice.
        </strong>{" "}
        FunderReady does not guarantee that following AI feedback will result in
        successful funding applications. Reviews are generated by AI models
        (Anthropic Claude) and may contain inaccuracies, omissions, or
        subjective assessments. You should always exercise your own judgement and
        seek professional advice where appropriate.
      </p>
      <p>
        We make no warranties about the accuracy, completeness, or reliability
        of AI-generated reviews. Funding decisions are made solely by the
        relevant funding bodies and are outside our control.
      </p>

      <h2>4. Your Account</h2>
      <p>
        You are responsible for maintaining the security of your account
        credentials. You must not share your account or allow others to access
        it. You are responsible for all activity under your account.
      </p>

      <h2>5. Intellectual Property</h2>
      <p>
        <strong>Your content:</strong> you retain full ownership of all content
        you submit, including application answers and supporting materials. By
        using the service, you grant us a limited licence to process your
        content solely for the purpose of providing the service (including
        sending text to our AI provider for review).
      </p>
      <p>
        <strong>Our content:</strong> the FunderReady platform, branding, and
        software are our intellectual property. AI-generated review feedback is
        provided for your use but may not be resold or redistributed as a
        standalone product.
      </p>

      <h2>6. Acceptable Use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Use the service for any unlawful purpose.</li>
        <li>
          Submit content that infringes the intellectual property rights of
          others.
        </li>
        <li>
          Attempt to circumvent usage limits, rate limits, or access controls.
        </li>
        <li>
          Reverse-engineer, scrape, or automated-access the service beyond
          normal use.
        </li>
        <li>
          Resell, sublicence, or redistribute the service or AI-generated
          outputs.
        </li>
      </ul>

      <h2>7. Subscriptions and Payment</h2>
      <p>
        Access to review features requires a Pro subscription or beta access
        granted by us. Subscription terms, pricing, and billing are managed
        through Stripe. We reserve the right to change pricing with 30 days&apos;
        notice.
      </p>

      <h2>8. Limitation of Liability</h2>
      <p>
        To the fullest extent permitted by law, FunderReady shall not be liable
        for any indirect, incidental, special, consequential, or punitive
        damages, including but not limited to loss of funding, revenue, or
        opportunity, arising from your use of the service.
      </p>
      <p>
        Our total liability for any claim arising from the service shall not
        exceed the amount you paid us in the 12 months preceding the claim.
      </p>

      <h2>9. Service Availability</h2>
      <p>
        We aim to provide a reliable service but do not guarantee uninterrupted
        access. We may suspend or modify the service for maintenance, updates,
        or other operational reasons. We will endeavour to provide reasonable
        notice of planned downtime.
      </p>

      <h2>10. Termination</h2>
      <p>
        You may delete your account at any time. We may suspend or terminate
        your account if you breach these terms. Upon termination, your right to
        use the service ceases immediately. We will delete your data in
        accordance with our Privacy Policy.
      </p>

      <h2>11. Changes to These Terms</h2>
      <p>
        We may update these terms from time to time. We will notify you of
        material changes by email or through the service. Continued use after
        changes take effect constitutes acceptance.
      </p>

      <h2>12. Governing Law</h2>
      <p>
        These terms are governed by the laws of England and Wales. Any disputes
        shall be subject to the exclusive jurisdiction of the courts of England
        and Wales.
      </p>

      <h2>13. Contact</h2>
      <p>
        For questions about these terms, contact us at{" "}
        <a href="mailto:hello@funderready.com">hello@funderready.com</a>.
      </p>
    </>
  );
}
