-- Gift links: single-use credit gift links generated by admins
CREATE TABLE IF NOT EXISTS public.gift_links (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  code text NOT NULL UNIQUE,
  credits integer NOT NULL CHECK (credits >= 1 AND credits <= 100),
  created_by uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz,
  redeemed_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  redeemed_at timestamptz
);

-- Fast lookup by code (used on every redemption attempt)
CREATE INDEX IF NOT EXISTS gift_links_code_idx ON public.gift_links (code);

-- RLS: no user-facing access — all reads/writes go through service role
ALTER TABLE public.gift_links ENABLE ROW LEVEL SECURITY;
